name: Repository Events
on:
  push:
    branches:
      - main
      - "feature/*"
      - "!bugfix/*" # exclude branches that start with 'bugfix/'
    #branches-ignore:
      #- "feature/experimental" # exclude the 'feature/experimental' branch
    paths:
      - "**.js"
  pull_request:
    types: [opened, assigned, reopened, synchronize]
  issues:
    types: [opened, closed]
jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3